version: "3.7"

services:
    shorty-api-public:
        build:
            context: ../.
            dockerfile: ./build/dev.Dockerfile
        command: public
        ports:
            - 40000:40000
        networks:
            - dev-net
        security_opt:
            - seccomp:unconfined
        labels:
            - traefik.enable=true
            - traefik.http.routers.shorty-api-public.rule=Host(`shorty.lvh.me`) && PathPrefix(`/api/public`)
            - traefik.http.routers.shorty-api-public.middlewares=api-public-prefix
            - traefik.http.services.shorty-api-public.loadbalancer.server.port=9000

networks:
    dev-net:
        external: true
