"api":
    "port": 80
"database":
    "host": "127.0.0.1"
    "port": 5432
    "user": ""
    "password": ""
    "dbname": ""
    "sslmode": "require"
    "max_open_conns": 0
    "max_idle_conns": 2
    "conn_max_lifetime": 0
"cache":
    "host": "127.0.0.1"
    "port": 6379
    "password": ""
    "db": 0
    "tls": false
